language: node_js
node_js:
  - 8
os: 
  - linux
dist: focal
#sudo: required

before_install:
  - docker build -t allanman408/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true allanman408/react-test npm test

after_success:
  - docker build -t allanman408/multi-client ./client
  - docker build -t allanman408/multi-nginx ./nginx
  - docker build -t allanman408/multi-server ./server
  - docker build -t allanman408/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push allanman408/multi-client
  - docker push allanman408/multi-nginx 
  - docker push allanman408/multi-server
  - docker push allanman408/multi-worker